services:
  - type: web
    name: brickworks-backend
    env: docker
    plan: free
    repo: https://github.com/Udayendra/BrickWorks
    branch: main
    dockerfilePath: ./Dockerfile  # Make sure this path is correct
    startCommand: "php artisan serve --host=0.0.0.0 --port=8080"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: brickworksdb-udayendrapal235-6ee7.e.aivencloud.com
      - key: DB_PORT
        value: 21986
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: yourpassword
      - key: MYSQL_ATTR_SSL_CA
        value: /var/www/backend/ca.pem
