services:
  - type: web
    name: brickworks-backend
    env: docker
    plan: free
    repo: https://github.com/yourusername/yourrepo
    branch: main
    buildCommand: "composer install && php artisan config:clear"
    startCommand: "php artisan serve --host 0.0.0.0 --port 8080"
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        value: brickworksdb-udayendrapal235-6ee7.e.aivencloud.com
      - key: DB_PORT
        value: 21986
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: yourpassword
      - key: MYSQL_ATTR_SSL_CA
        value: /var/www/backend/ca.pem
